### ISSUE TITLE
Github Branch Protection Fails for Free Users

### ISSUE THREAD

**Issue by bwsdm** [ALT-F4-LLC/terraform-github-repository#5]
This doesnt necessarily stop anything as far as I can tell, but when you are a free user with a private repo you dont have branch protection options and when running the plan it fails to create the branch protection:
![image](https://github.com/ALT-F4-LLC/terraform-github-repository/assets/2353927/474c19d0-c705-4dae-841d-c03eec249a77)

**Comment by erikreinert** [comment]
Merged https://github.com/ALT-F4-LLC/terraform-github-repository/pull/7 to fix this.

Thank you for the help!
